
services:
  - docker:dind

image: docker:latest

stages:
  - build
  - test
  - prod

variables:
  GITLAB_INSTANCE_ADDRESS: "https://gitlab.com"

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE

deploy-test:
  stage: test
  tags:
    - swarm-manager
  environment:
    name: test
  variables:
    PUBLISHED_PORT: 8181
  script:
    - echo Deploying to environment $CI_ENVIRONMENT_NAME ...
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker stack deploy --with-registry-auth -c docker-compose.yml $CI_ENVIRONMENT_NAME

deploy-prod:
  stage: prod
  tags:
    - swarm-manager
  environment:
    name: prod
  variables:
    PUBLISHED_PORT: 8282
  when: manual
  script:
    - echo Deploying to environment $CI_ENVIRONMENT_NAME ...
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker stack deploy --with-registry-auth -c docker-compose.yml $CI_ENVIRONMENT_NAME
